pipeline:
    name: basic piepline
    identifier: basic_piepline
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: basic
              identifier: basic
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8scluster
                          namespace: harness-delegate-pmdemo
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: echo
                                identifier: echo
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: <+input>
                                    command: echo "<+codebase.sourceBranch>"
                                    privileged: <+input>
                                when:
                                    stageStatus: Success
                                    condition: <+codebase.sourceBranch> != "null"
                                failureStrategies: []
                          - step:
                                name: zxczxc
                                identifier: zxczxc
                                template:
                                    templateRef: new_step_name
                                    versionLabel: "3.0"
                                    templateInputs:
                                        type: Run
                                        spec:
                                            envVariables:
                                                env1: <+input>
    properties:
        ci:
            codebase:
                connectorRef: account.Keen_jhttp
                build: <+input>
