pipeline:
  name: basic piepline
  identifier: basic_piepline
  projectIdentifier: Product_Demos_CIE
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: basic
        identifier: basic
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: echo2
                  identifier: echo
                  spec:
                    connectorRef: account.nofar_dockerhub
                    image: <+input>
                    shell: Sh
                    command: echo "<+codebase.sourceBranch>"
                    privileged: <+input>
                  when:
                    stageStatus: Success
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - parallel:
        - stage:
            name: queue test
            identifier: queue_test
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: Queue
                      name: s1
                      identifier: s1
                      spec:
                        key: abc
                        scope: Stage
                      timeout: 10m
            tags: {}
        - stage:
            name: queue2 stage
            identifier: queue2_stage
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: Queue
                      name: queue
                      identifier: queue
                      spec:
                        key: abc
                        scope: Stage
                      timeout: 10m
            tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Keen_jhttp
        build: <+input>
