pipeline:
  name: basic piepline
  identifier: basic_piepline
  projectIdentifier: Product_Demos_CIE
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: queue test
            identifier: queue_test
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: Queue
                      name: s1
                      identifier: s1
                      spec:
                        key: abc
                        scope: Stage
                      timeout: 10m
            tags: {}
        - stage:
            name: queue2 stage
            identifier: queue2_stage
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: Queue
                      name: queue
                      identifier: queue
                      spec:
                        key: abc
                        scope: Stage
                      timeout: 10m
            tags: {}
