pipeline:
    name: basic piepline
    identifier: basic_piepline
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: basic
              identifier: basic
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8scluster
                          namespace: harness-delegate-pmdemo
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: echo2
                                identifier: echo
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    shell: Sh
                                    command: echo "hey"
                                when:
                                    stageStatus: Success
                                    condition: <+codebase.sourceBranch> != "null"
                                failureStrategies: []
        - stage:
              name: aaa
              identifier: aaa
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      useFromStage: basic
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: fail
                                identifier: fail
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    shell: Sh
                                    command: exit 1
