connector:
  name: org git connector keen
  identifier: BS1223
  description: ""
  orgIdentifier: default
  projectIdentifier: Product_Demos_CIE
  type: Github
  spec:
    url: https://github.com/keen-software
    validationRepo: jhttp
    authentication:
      type: Http
      spec:
        type: OAuth
        spec:
          tokenRef: harnessoauthaccesstoken_github_1702240591722
    apiAccess:
      type: OAuth
      spec:
        tokenRef: harnessoauthaccesstoken_github_1702240591722
    executeOnDelegate: false
    type: Account
