pipeline:
    name: go demo v2_0
    identifier: go_demo_v2_0
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Build Test and Push
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: see local images
                                identifier: see_local_images
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: docker
                                    command: docker images
                                    privileged: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8scluster
                          namespace: harness-delegate-pmdemo
                  serviceDependencies:
                      - identifier: DIND_service
                        name: DIND service
                        type: Service
                        spec:
                            connectorRef: account.nofar_dockerhub
                            image: docker:dind
                            privileged: true
                  sharedPaths:
                      - /var/run
              variables:
                  - name: PLUGIN_NO_PUSH
                    type: String
                    value: "true"
        - stage:
              name: Run Integration Test
              identifier: Run_Integration_Test
              type: CI
              spec:
                  cloneCodebase: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test connection to server
                                identifier: test_connection_to_server
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: curlimages/curl:7.69.1
                                    command: |-
                                        sleep 5
                                        curl localhost:8080
                                    privileged: false
                          - step:
                                type: Run
                                name: echo
                                identifier: echo
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    command: echo "hello"
                                    privileged: false
                  serviceDependencies:
                      - identifier: runhelloworldserver
                        name: Run Hello World Server
                        type: Service
                        spec:
                            connectorRef: account.nofar_dockerhub
                            image: bluebbb/godemo:<+pipeline.sequenceId>
                  infrastructure:
                      useFromStage: Test_Build_and_Push
                  sharedPaths:
                      - ""
              description: running integ tests
    properties:
        ci:
            codebase:
                connectorRef: account.goHelloWorldServer_repo
                build: <+input>
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
