pipeline:
    name: go demo v2_0
    identifier: go_demo_v2_0
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Build Test and Push
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Go Build
                                identifier: Go_Build
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: golang:1.15
                                    command: |-
                                        set +e
                                        go get gotest.tools/gotestsum
                                        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                                        exit 0
                                    privileged: false
                                when:
                                    stageStatus: Success
                                failureStrategies: []
                          - step:
                                type: Run
                                name: print content
                                identifier: print_content
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    command: ls -a
                                    privileged: false
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build and push image to DockerHub
                                identifier: Build_and_push_image_to_DockerHub
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    repo: bluebbb/godemo
                                    tags:
                                        - latest
                                    optimize: true
                          - step:
                                type: Plugin
                                name: scan container
                                identifier: scan_container
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: plugins/github-actions
                                    privileged: true
                                    settings:
                                        uses: aquasecurity/trivy-action@master
                                        with:
                                            image-ref: bluebbb/godemo:latest
                                            format: table
                                            exit-code: "1"
                                            ignore-unfixed: true
                                            vuln-type: os,library
                                            severity: CRITICAL,HIGH
                          - step:
                                type: Run
                                name: see local images
                                identifier: see_local_images
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: docker:dind
                                    command: docker images
                                    privileged: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8scluster
                          namespace: harness-delegate-pmdemo
                  serviceDependencies:
                      - identifier: DIND_service
                        name: DIND service
                        type: Service
                        spec:
                            connectorRef: account.nofar_dockerhub
                            image: docker:dind
                            privileged: true
                  sharedPaths:
                      - /var/run
              variables:
                  - name: PLUGIN_NO_PUSH
                    type: String
                    value: "true"
        - stage:
              name: Run Integration Test
              identifier: Run_Integration_Test
              type: CI
              spec:
                  cloneCodebase: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test connection to server
                                identifier: test_connection_to_server
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: curlimages/curl:7.69.1
                                    command: |-
                                        sleep 5
                                        curl localhost:8080
                                    privileged: false
                          - step:
                                type: Run
                                name: echo
                                identifier: echo
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    command: echo "hello"
                                    privileged: false
                  serviceDependencies:
                      - identifier: runhelloworldserver
                        name: Run Hello World Server
                        type: Service
                        spec:
                            connectorRef: account.nofar_dockerhub
                            image: bluebbb/godemo:<+pipeline.sequenceId>
                  infrastructure:
                      useFromStage: Test_Build_and_Push
                  sharedPaths:
                      - ""
              description: running integ tests
    properties:
        ci:
            codebase:
                connectorRef: account.goHelloWorldServer_repo
                build: <+input>
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
