inputSet:
  identifier: "main_branch_input_set"
  pipeline:
    identifier: "java_http_client"
    properties:
      ci:
        codebase:
          build:
            type: "branch"
            spec:
              branch: "main"
  name: "main branch input set"
  orgIdentifier: "default"
  projectIdentifier: "Product_Demos_CIE"
