template:
    name: Run Test
    identifier: Run_Test
    versionLabel: "2.0"
    type: Step
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    spec:
        type: Run
        description: this is a step that run one integration test
        spec:
            connectorRef: account.nofar_dockerhub
            image: alpine
            command: echo "test2"
            privileged: false
            envVariables:
                env1: <+input>
