template:
    name: test
    identifier: test
    versionLabel: "1.0"
    type: Step
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    spec:
        type: Run
        spec:
            connectorRef: account.nofar_dockerhub
            image: alpine
            command: echo "hello"
            privileged: false
