template:
    name: test1234
    identifier: test1234
    versionLabel: "2.0"
    type: Step
    projectIdentifier: Product_Demos_CIE
    orgIdentifier: default
    tags: {}
    spec:
        type: Run
        description: asdf
        spec:
            connectorRef: account.nofar_dockerhub
            image: alpine
            command: echo "hey"
